Full gpt transcripts logged
AbanteAI/mentat pull request #120
Opened 2023-10-01 12:49 UTC by jakethekoenig

This is a little redundant because the user interactions and LLM responses are logged elsewhere but:
1. Going forward I don't think we should assume we can reconstruct the conversational state from user interactions and LLM responses. We may add features like summarization of code edits to save tokens or not send user requests verbatim (this already happens to some extent with special tokens like q.
2. It seems like a nice QoL feature to log the transcripts in the exact format needed for interaction with OpenAI apis.

2023-10-02 16:44 UTC, PCSwingle approved these changes
Thanks for adding this! This is definitely something I think we'll find super useful

2023-10-03 00:03 UTC, granawkins requested changes

2023-10-03 00:03 UTC, granawkins commented on mentat/logging_config.py
> +    transcripts_handler = logging.FileHandler(logs_path / "transcripts.log")
```suggestion
    transcripts_handler = logging.FileHandler(logs_path / f"transcript_{timestamp}.log")
```

My one suggestion - makes it easier to review specific logs for debugging.

2023-10-03 20:52 UTC, biobootloader commented
Nice, makes sense to have a verbatim log instead of having to try to piece things together.

Is there a reason people would want to turn this off / not turn it on? Maybe we don't need an option

2023-10-05 15:09 UTC, jakethekoenig commented
> Nice, makes sense to have a verbatim log instead of having to try to piece things together.
> 
> Is there a reason people would want to turn this off / not turn it on? Maybe we don't need an option

I was thinking the transcripts would grow quadratically and it'd maybe be better to not include them by default but I guess they grow quadratically in number of conversational steps which should be pretty small. I think you're right there's no need to have this off by default so there's no need to have the setting.

2023-10-05 15:17 UTC, merged